---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sabnzbd
  - radarr
  - plex
  - overseerr
  - sonarr
  - envoyextensionpolicy.yaml
  - schedule.yaml
  - securitypolicy.yaml
  - secret.yaml
