---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: usenet
spec:
  ports:
    - port: 5055
      targetPort: 5055
  selector:
    app: seerr
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  type: ClusterIP
