---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-path-provisioner
  - nfs-subdir-external-provisioner
  - metrics-server
  - oauth2-proxy
  - cert-manager
  - envoy-gateway
  - metallb
  - falco
  - coredns
  - cilium
  - ingress-nginx
