---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-cluster.yaml
  - prometheusrule.yaml
  - scheduledbackup.yaml
  - objectstore.yaml
  - configmap.yaml
  - secret.yaml
