---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - falco.yaml
  - k8up.yaml
  - keycloak.yaml
  - renovate.yaml
  - envoy-gateway-system.yaml
  - ingress-nginx.yaml
  - gitlab.yaml
  - nextcloud.yaml
  - oauth2-proxy.yaml
  - storage-system.yaml
  - metallb-system.yaml
  - immich.yaml
  - kube-system.yaml
  - usenet.yaml
  - cloudflare-operator.yaml
  - cnpg-system.yaml
  - cert-manager.yaml
  - teslamate.yaml
  - minio.yaml
  - monitoring.yaml
  - cilium.yaml
