---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webhook
  - flux-system
  - namespaces
  - ocirepositories
  - gitrepositories
  - kustomizations
  - helmrepositories
  - notifications
  - cluster-settings.yaml
  - cluster-secrets.yaml
