---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-services
  - gatewayclass.yaml
  - httproute.yaml
  - envoypatchpolicy.yaml
  - cronjob.yaml
  - helmrelease.yaml
  - gateway.yaml
  - clienttrafficpolicy.yaml
  - secret.yaml
  - persistentvolumeclaim.yaml
  - ciliumnetworkpolicy.yaml
  - envoyproxy.yaml
