---
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-valkey
  namespace: envoy-gateway-system
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: envoy-gateway-valkey
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  type: ClusterIP
