---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg
  - cloudflare-operator
  - kube-prometheus-stack
  - cert-manager
  - barman-cloud-plugin
  - metallb
  - k8up
