---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
  - helmrelease.yaml
  - envoyextensionpolicy.yaml
  - dnsrecords.yaml
  - tcproute.yaml
  - secret.yaml
